### ISSUE TITLE
Merging this repo with the official one ;)

### ISSUE THREAD

**Issue by rande** [ibrows/IbrowsSonataTranslationBundle#1]
Hello,

I just found out this bundle and it does one goal of the SonataTranslationBundle : https://github.com/sonata-project/SonataTranslationBundle : integrates Lexik Translation Bundle into sonata.

So, do you want to merge this code into the official one ? This will also require some re-factorisations to respect PSR conventions and add some documentations.

We also have internal code to complete this bundle, like exporting and importing data.

The idea is also to deprecate this bundle and you can become a contributor to https://github.com/sonata-project/SonataTranslationBundle.

What do you think ?

**Comment by mikelohmann** [comment]
+1

**Comment by Gladhon** [comment]
For me, it  looks like that SonataTranslationBundle try to get Admininterface to translate Models. Which is nice and useful. But our this Bundle just integrates Lexik Translation Bundle into SonataAdmin. I dont like the idea to merge them together into one repo. 
But it would be nice if the 2 bundles with diffrent target could share some code or something like that
