### ISSUE TITLE
In sonata admin 3.x use of old fontawesome classes 

### ISSUE THREAD

**Issue by soipo** [ibrows/IbrowsSonataTranslationBundle#11]
Hi , 
in bootstrap-editable.min.js there are two classes icon-ok and icon-remove which are not going to work for sonata admin 3.x, adding also the new classes would be a very quick fix.

**Comment by Gladhon** [comment]
thx for information, maybe you can make a pull request in bootstrap-editable.js ?

**Comment by soipo** [comment]
I have just did it. Thanks for the help with this bundle
