### ISSUE TITLE
Uncaught TypeError: Cannot read property 'template' of undefined

### ISSUE THREAD

**Issue by 4ssil** [ibrows/IbrowsSonataTranslationBundle#13]
Hi,

I'm facing an issue where a javascript error is triggered on the translations admin page:
```
Uncaught TypeError: Cannot read property 'template' of undefined
    at bootstrap-editable.min.js:2
    at bootstrap-editable.min.js:2
```
The error seems to prevent ok and cancel icons from loading which results in this: [http://i.imgur.com/yWIS53r.png](url)
Clicking the buttons results in the corresponding action being taken, but it's confusing for end users.

I'm using 
```
"sonata-project/admin-bundle": "^3.0"
"ibrows/sonata-translation-bundle" : "dev-master"
```
and I had the same issue with sonata admin 2.3 as well.

The icons show up on other admins and no JS error is thrown to the console which points me to IbrowsSonataTranslationBundle as the one with an issue.

**Comment by DekaBraZ** [comment]
Same here, 

```
"sonata-project/admin-bundle": "^3.22",
"ibrows/sonata-translation-bundle": "dev-master",
```
Almost a year has passed and nothing changed.

**Comment by 4ssil** [comment]
@mikemeier can you please help ?

**Comment by jigneshv34** [comment]
Make sure to use x-editable/dist/bootstrap3-editable/js/bootstrap-editable.js for bootstrap3.

Ref : https://github.com/nate-strauser/meteor-x-editable-bootstrap/issues/11

**Comment by dennisgarrn** [comment]
we fixed this in: https://github.com/ibrows/IbrowsSonataTranslationBundle/tree/symfony-3.4
