### ISSUE TITLE
Compatibility with Symfony 3

### ISSUE THREAD

**Issue by MauroCasula** [ibrows/IbrowsSonataTranslationBundle#14]
The option "empty_value" and the view variables "empty_value" and"empty_value_in_choices" has be removed in Symfony 3.0. 

To make this compatible the only change needed in on Admin/ORMTranslationAdmin.php line 95. Remove the empty_value key or replace it with the new key "placeholder".

Thanks in advance.

**Comment by emgiezet** [comment]
I will make a PR for this

**Comment by dennisgarrn** [comment]
Please use: https://github.com/ibrows/IbrowsSonataTranslationBundle/tree/symfony-3.4
