### ISSUE TITLE
Errror with sonata-admin 2.4

### ISSUE THREAD

**Issue by INHack20** [ibrows/IbrowsSonataTranslationBundle#4]
With repo "sonata-project/admin-bundle": "2.4.*@dev"
Runtime Notice: Declaration of Ibrows\SonataTranslationBundle\Controller\TranslationCRUDController::editAction() should be compatible with Sonata\AdminBundle\Controller\CRUDController::editAction($id = NULL, Symfony\Component\HttpFoundation\Request $request = NULL)

proposal:
Create a compatible 2.x branch with sonata 2.4 and update composer.json requirements.

**Comment by Gladhon** [comment]
Your problem have been fixed, can you test it please ?
version: 1.0.13
